### ISSUE TITLE
Generic database mapper or specific one ?

### ISSUE THREAD

**Issue by tontof** [TomBZombie/Maphper#10]
As you use PDO and not mysqli, I was thinking it would be a generic mapper but you use specific MYSQL syntax which is not compatible with other drivers (actually I've just tested with sqlite but I guess SHOW WARNINGS, ON DUPLICATE KEY do not work with others too).

I think that all the common stuff (select, insert, delete) and also the creation of the tables can be more or less generic but I guess that editmode options has to be database driver specific. Sqlite table modifications are for example very limited.

As a work in progress, I was wondering if you expect your database mapper to be generic or very specific to mysql ?

**Comment by TomBZombie** [comment]
I was thinking about this the other day and there's a couple of ways of doing it:

1) Have a DataSource for each database type so you'd have MySQLDataSource, SQLiteDataSource, etc. This works but there's no easy way of achieving this and sharing the similar code between the mappers, other than inheritance which is generally a messy solution... it also means making the DatabaseDataSource abstract

2) Make an interface like DataBase which looked something like this:

```php
interface DataBase {
	
	public function save($tableName, $data);
	public function getErrors();
	public function createTable($name);
	public function addColumn($name, $type);
	public function find($where, $group = null, $limit = null, $offset = null);

}
```

That way, you could create a class like:


```php
class MySQLDatabase implements Database {
    public function __construct(PDO $pdo) {

    }
}
```

Then you could pass the DataBase implementation into the DatabaseDataSource and instead of calling $pdo->query('CREATE TABLE') it would call $this->database->createTable('name');

This is the ideal solution from an OOP perspective but the problem with this approach is that it makes the mapper initialisation quite messy and verbose:

```php
$mapper = new Maphper(new DatabaseDataSource(new MySqlDatabase(new PDO(....)), 'table', 'pk);
```

Having 3 levels (Maphper, Data Source, PDO) was pushing it as my goal was simplicity as it requires a  basic understanding of the implementation of Maphper in order to use it, I'd rather people could use it without any knowledge of how it works internally.


I think maybe a happy-medium (although slightly anti-OOP) would be to have the DatabaseDataSource construct an implementation of Database based on the type of database PDO is connected to... for example:

```php
class DatabaseDataMapper implements DataSource {
	

	pubic function __construct(PDO $pdo, $table, $pk) {
		$this->db = $this->getDb($pdo);
	}

	private function getDb(PDO $pdo) {
		$driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
		if ($driver == 'mysql') return new MySqlDataBase($pdo);
		else if ($driver == 'sqllite') return new SqliteDatabase($pdo);

	}

	public function findByField(array $fields, $options = [], $mode = null) {
		//whatever
		$this->db->select($where, $limit, $offset, $group);
	}
}
```

Not ideal from an OOP perspective because the DB driver cannot be mocked for testing but from a usability point of view I think it's a happy compromise. Happy to listen to suggestions!

**Comment by tontof** [comment]
Before discovering maphper, I was looking at https://github.com/j4mie/idiorm/ and https://github.com/j4mie/paris
I definitely prefer your approach but I like the generic part of idiorm which leads to an easy use for end user and easy to maintain for developer.

I think that the creation of specific MySqlDatabase, SqliteDatabase, etc. risks to be difficult to maintain using PDO. For end user that's not a problem, but as most of the code can be generic with PDO, I think that having a Database class generic is great even if some features are no available for some drivers (for example, the editmode can not be used with sqlite to modify fields)

That's why I think that modifying your Database class to work with other drivers is better than creating specific MySqlDatabase, SqliteDatabase classes. From my point of view having a MysqliDatabase class using http://php.net/manual/en/book.mysqli.php and Sqlite3Database using http://php.net/manual/en/book.sqlite3.php and so on for others http://php.net/manual/en/refs.database.vendors.php is a better approach as it will (should) improve performance for specific database using specific libraries.

That way people can use Maphper using a generic Database (PdoDatabase) class without knowledge of internally code and if people looks for performance they can propose you a specific Datasource using a specific library.

**Comment by TomBZombie** [comment]
I've started work on this. I've separated out all queries from the DatabaseDataSource such that SQLite/Oracle/MSSQL/etc which are supported by PDO can also be used with Maphper.

To enable SQLite support the following class needs to be completed:

```php
<?php
namespace Maphper\DataSource;
class SqliteAdapter implements DatabaseAdapter {
//...
}
```

I don't know much about Sqlite but I'll have a go at implementing this when I get a chance. Alternatively if you implement it please send a pull request :)

**Comment by TomBZombie** [comment]
Looking at the Sqlite docs, I'm not sure why create table/alter table couldn't be used ( https://www.sqlite.org/lang_altertable.html ) it doesn't look like CREATE TABLE IF NOT EXISTS is supported but that's not a huge issue, it just means doing SHOW TABLES (or whatever the sqlite equivalent is) to find out if the table exists prior to trying to create it.

**Comment by tontof** [comment]
CREATE TABLE IF NOT EXISTS  works (if I remember), the problem is MODIFY which is not possible with sqlite (ADD is ok but not with all sqlite3 version).

I will look at your adapter and work on SqliteAdapter to send a pull request. I will try to find time to do this during the week.

**Comment by TomBZombie** [comment]
didn't know that. It looks like the lack of MODIFY may be able to be worked around: http://stackoverflow.com/questions/2685885/sqlite-modify-column Create another table, copy the records, remove the old table and rename the new one.

For Maphper's use case this inefficiency doesn't really matter as it will only happen during development on the occasions where a column type is changed.

**Comment by tontof** [comment]
OK I will look at that work around.
I've started to code the sqliteadapter and I wanted to test using your DatabaseTest but I need to also modify it. For example 'SHOW TABLES' does not exist in tableExists function :-)
http://www.sqlite.org/faq.html#q7

(For now, I'm able to create table and insert some data)

I was wondering how do you test your DatabaseTest with phpunit ? There is no autoload.php for the --bootstrap option ?

Well I manage it with an ugly work around by adding required files in test file but I know there should be a better way.
Did you use your Axel autoloader ?

**Comment by TomBZombie** [comment]
I've just got a bootstrap file that includes the required files, I didn't include it in the project because it's the one I'm using is fairly specific to Eclipse PDT that I'm currently using:

This should work:

```php
require_once 'maphper.php';
require_once 'relation.php';
require_once 'multipk.php';
require_once 'datasource.php';
require_once 'datasource/database.php';
require_once 'datasource/databaseadapter.php';
require_once 'datasource/mysqladapter.php';
require_once 'relation/one.php';
```

You may need a chdir('/path/to/maphper/'); I may add an autoload but it seems a bit pointless for such a (currently) small project.

at the top.

**Comment by garrettw** [comment]
I vote for your "happy-medium (although slightly anti-OOP)" option. It may not be ideal, but it does eliminate what seems like an unnecessary extra level of complexity for the end developer. Relying on PDO to dictate which `*Database` is used seems reasonable.

I'd add that when I discovered you were writing a DataMapper-pattern ORM, I was fairly excited; I know your code to be of high quality in terms of OOP and speed, and I learned the benefits of DataMapper over ActiveRecord from your website (and there are few, if any, decent DataMapper alternatives to Doctrine out there currently!). So thanks for creating this. :smile:

**Comment by TomBZombie** [comment]
Thanks Garret :) 

After I implemented it I actually made it slightly more flexible than my proposal above.

The constructor to DataSource\Database now looks like this:

```php
	public function __construct($db, $table, $primaryKey = 'id', array $options = []) {
		if ($db instanceof \PDO) $this->adapter = $this->getAdapter($db);
		else $this->adapter = $db;
//...
}


private function getAdapter(\PDO $pdo) {
		$adapter = '\\Maphper\\DataSource\\' . $pdo->getAttribute(\PDO::ATTR_DRIVER_NAME) . 'Adapter';
		return new $adapter($pdo);
	}
```


so if you pass a PDO instance as the $db parameter the adapter is worked out on-the-fly based on the PDO connection. However, you can still pass an instance of a class that implements DatabaseAdapter if you prefer.

This is a best of both worlds approach, you can pass a PDO instance and it gets self-configured or you can pass an explicit instance that implements the adapter. This has the added benefit of potentially supporting MySQLi or other database implementations by making a class which implements  DatabaseAdapter accordingly. The added benefit of all of this is that DataSource\Database is no longer coupled to PDO.

**Comment by tontof** [comment]
```
OK (32 tests, 116 assertions)
```
With sqliteadapter

There are 2 remaining problems:
- As your DatabaseTest does not handle column modification yet, I did not implement it yet (BTW even if it's not a really unit test, it was very helpful !)
- I had a problem for performing the insert and update if it fails queries. In the insert function, I have no information concerning the primary key and so it works for now because I supposed the id was 'id' field which is not right for the general case.

Concerning the adapter approach, I first thought it was a really great idea, but now, I'm wondering because there are some code in the database.php that might pose problem ? For example there are some code as in deleteById that are PDO oriented ```' = :id'``` for parameter binding ?

**Comment by TomBZombie** [comment]
Thanks for the work!

> As your DatabaseTest does not handle column modification yet, I did not implement it yet (BTW even if it's not a really unit test, it was very helpful !)

I'll try to add some tests for that :)

> I had a problem for performing the insert and update if it fails queries. In the insert function, I have no information concerning the primary key and so it works for now because I supposed the id was 'id' field which is not right for the general case.

That's a very good point. Maybe the interface for the insert function should be:

```php
public function insert($table, array $primaryKey, $data);
```
(I've tried to keep primary keys as arrays everywhere to standardise and enforce support for composite keys)

> I'm wondering because there are some code in the database.php that might pose problem ? For example there are some code as in deleteById that are PDO oriented ' = :id' for parameter binding ?

I think you're right... I'll have a think about this.

The problem is, Maphper supports some very advanced (Currently undocumented) filtering like this:

```php
$blogs->filter([
\Maphper\Maphper::FIND_OR => [
	\Maphper\Maphper::FIND_LIKE => [
		'title' => 'foo',
		'cotent' => 'bar'	
	],
	\Maphper\Maphper::FIND_EXACT => [
		'title' => 'baz'
	]
]
]);
```

which generates (in theory, it needs some tweaking!) SELECT * FROM blogs WHERE (title LIKE '%foo%' AND content LIKE '%bar%') OR title = 'baz'



by taking out the id = :id from the database mapper it means either... repeating this complex logic in each adapter or not having this kind of filtering so easily... I'll have a think.


That said, there's nothing wrong with someone doing this:

```php
class MySqliAdapter {

	public function delete($table, array $criteria, $args, $limit = null, $offset = null) {
		$limit = $limit ? ' LIMIT ' . $limit : '';
		
		$query = implode(' AND ', $criteria);
		
		foreach ($args as $key => $value) {
			$query = str_replace($key, '"' . $this->mysqli->real_escape_string($value) . '"", $query);
		}
		$this-mysqli->query('DELETE FROM ' . $table . ' WHERE ' . $query . $limit, $args);
	}


}
```

the adapter must be given fields/values separately in order to escape them properly for the specific implementation. It also needs the logic for LIKE, =, IN() etc...

**Comment by tontof** [comment]
Well, my PDO oriented example was indeed wrong, as it was just an adapter function parameter, but this was the idea. Filtering will indeed be difficult to handle correctly.

I have some space to tab modification to perform before the PR and I will let you decide for the interface modification. Maybe you will see a better approach that does not need change.

**Comment by TomBZombie** [comment]
The simplest way is the interface modification. Since there is only one class using the interface at the moment, changing it now is better than changing it later

**Comment by tontof** [comment]
OK, do you want me to do it with the PR ?

**Comment by TomBZombie** [comment]
Yeah, base it on the code above and implement the insert with the $primarykey argument. I'll adjust the MySqlAdapter accordingly.

**Comment by tontof** [comment]
I guess the issue can be closed now
