### ISSUE TITLE
Tests improvement

### ISSUE THREAD

**Issue by tontof** [TomBZombie/Maphper#14]
I did not add unit tests but I've encountered 2 problems during my code testing.
- A field is not updated after setting it to null
```
$blogs = new \Maphper\Maphper($blogSource);
$blog = $blogs[1];
$blog->title = null;
$blogs[1] = $blog;
```
title is not modified.
- The table type is not changed
```
$blogs = new \Maphper\Maphper($blogSource);
$blog->value = 10;
$blogs[] = $blog;
```
value type is integer
```
$blogs = new \Maphper\Maphper($blogSource);
$blog->value = 'ten';
$blogs[] = $blog;
```
value type is integer but value is 'ten'
(I guess this last behavior is specific to sqlite, but just in case you want to add more tests)

**Comment by TomBZombie** [comment]
thanks, I've fixed the issue with inserting NULL values and added tests for changing column type.

Looking at SqliteAdapte, does SQLite support INSERT...SELECT? It may make the alterDatabase method a little simpler?

If so, instead of 

```
$results = $this->pdo->query('SELECT * FROM '.$table);
```
 which in a large db may be very inefficient (i don't know how PDO works internally, it may be fine but either way it would be tidier code if we can...)

can this entire block be replaced with:

$this->pdo->query('INSERT INTO ' . $this->quote($table . $affix) .' SELECT * FROM ' . $this->quote($table))?

**Comment by tontof** [comment]
I don't know exactly for the INSERT...SELECT but from the doc I think it's possible: https://www.sqlite.org/lang_insert.html
I will have a try tomorrow I did not think about that better option.

**Comment by tontof** [comment]
I think, it's ok
https://github.com/TomBZombie/Maphper/pull/18
