### ISSUE TITLE
Error management with PDO (and MySqlAdapter)

### ISSUE THREAD

**Issue by LexLythius** [TomBZombie/Maphper#15]
Today, after making a silly DSN string mistake, whereby rows failed to be inserted, I realized that, since PDO's default behaviour (at least in PHP 5.5) is *not* to throw an exception (PDO::ERRMODE_SILENT), this code in MySqlAdapter
```php
		try {
			if (count($args) > 0) $res = $stmt->execute($args);
			else $res = $stmt->execute();
			return $stmt->fetchAll(\PDO::FETCH_OBJ);
		}
		catch (\Exception $e) {
			return [];
		}
```
does not work as expected. Of course, this works:
```php
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$blogs = new Maphper(new Database(new MySqlAdapter($pdo), 'blogs', 'id'));
```
but we don't want it broken by default.

The second issue is that thrown exception should probably not be quietly ignored. Note that SHOW WARNINGS (used by getErrors method) did not return any clue about the real issue:
```
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected
```
I think we should have an $errors property to hold actual errors for the last statement and return that, and maybe add a separate getWarnings method.

**Comment by TomBZombie** [comment]
an errors/warnings collector makes sense. As an alternative, I was thinking of catching specific errors using MySQL error codes


```php
 try {            if (count($args) > 0) $res = $stmt->execute($args);
            else $res = $stmt->execute();
            return $stmt->fetchAll(\PDO::FETCH_OBJ);
        }
 catch (\PDOException $e) {
            // get MySQL error code
            $code = ...;
            if ($code == INVALID_TYPE || $code == TABLE_NOT_FOUND || $code == COLUMN_NOT_FOUND) {
//alter database
}
else throw $e;
        }
```


For ERRMode, I did have DatabaseDataMapper setting it in __construct()... but it feels like action at a distance... as it will affect anywhere that instance of PDO is used. I wonder if there's a way to set ERRMODE on a per-query basis?

**Comment by TomBZombie** [comment]
After thinking about this some more I think the error handling may need a redesign.

Originally I made Maphper silent in the spirit of jQuery ( $('.foo').animate() ) doesn't cause an error even if no elements match .foo. Similarly, I wanted to be able to use foreach ($mapper->filter(['a' => 'b']) even where no 'a' column exists, it would just give you zero results. This is to tally with the databases being fluid (at least with editmode on) such that what columns exist in the database don't really matter.

This same is true of tables. Maphper should be able to use

```php
$mapper = new \Maphper\Maphper(new DatabasedataMapper($pdo, 'tablename', 'id', ['editmode' => true]));

function find() {
$mapper->filter(['a' => 'b']);
}

function create() {
   $obj = new stdClass;
   $obj->a = 'b';
   $mapper[] = $obj;
}
```

With exceptions/errors calling

```php
create();
find();
```

Will work, but reversing the order of method calls will not

```php
find();
create();
```

Because the table may not exist until create() has been called. This inconsistency was what I was trying to avoid but I wonder if it's actually more confusing to do it this way.

**Comment by LexLythius** [comment]
jQuery's idea of operating on empty sets for given selectors is excellent for HTML, but we have a few differences:
 - the analogy between jQuery and DB fails as `SELECT foo, bar FROM table` would be equivalent to `$('.foo,.bar')`: with missing `bar` field/element, jQuery would still return matches for `.foo`, whereas DB would return nothing because of a hidden error (at least for all enforced schema DBMSs).
 - in our case, failure may be some precondition (such as db structure mismatch, failed connection, insufficient table access, etc), not the query syntax in itself; when this happens, suppressed debug info becomes necessary.
 - jQuery operates on HTML elements that are usually volatile, while we deal with persistent side effects, so while jQuery's failure is normally apparent and harmless, silent DB failure is likely only noticed after the fact because of lost data, for great user's amusement.

We could try and go over [specific DB errors](http://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html) trying to filter those that are recoverable, but I think that would be too much.

At least I would provide a configuration option on how to manage errors: silent, rethrow and (maybe) return false. In all cases errors/warnings should be queryable.

**Comment by TomBZombie** [comment]
Maphper never deletes or drops anything without explicitly calling delete so I think "lost data" isn't really an issue. 

> For me, being able to do $table[$id]->$field while every precondition is met is expressive, easy and powerful enough that I don't require a whole lot more syntactic sugar.

So if $table[$id] isn't set what should happen? The sensible approach is that $table[$id] should return null of there's no record for that ID. Fair enough, and my point really is that the same behaviour should occur for whatever reason the record cannot be retrieved. Whether the record doesn't exist in the table or the table doesn't exist or some other reason $table[$id] should return either null or the object as a matter of consistency. This is especially important as the table can be created on the fly, so just because the table doesn't exist yet, it may later in the script.

As the behaviour for altering/creating the database relies on knowing when there was an error I think rethrowing if $e->getCode() is not in a predetermined list is probably the easiest. You're right that suppressing privilege/connection errors is a bad idea. In my opinion re-throwing in this case is preferable to storing a list of caught exceptions in $mapper->getErrors() or similar as it's immediately obvious rather than having to log the errors/change the code to find out what the error is.

That said, I'm going to think about a better way to handle this.

I think your suggestion for setting ERRMODE is the best available unfortunately. I've just added a commit that does this. I think it's a better option that setting ERRMODE to exception if someone is relying on it being different elsewhere in the application that the PDO instance may be used.

> At least I would provide a configuration option on how to manage errors: silent, rethrow and (maybe) return false. In all cases errors/warnings should be queryable.

As PDO is a requirement I think the easiest and most logical approach is just to use the behaviour set in $pdo->getAttribute(\PDO::ATTR_ERRMODE); rather than having a setting for PDO and a setting for Maphper.

**Comment by TomBZombie** [comment]
A little further thought, I think there's a really simple solution to this without needing to manually examine error codes:

- run the insert query
- use try/catch to catch any exception
- If an exception is caught run the alterDatabase() method 
- Run the insert query again but outside try/catch
- if it fails the second time the exception will just be thrown normally (or be silent, or a warning depending on PDO::ATTR_ERRMODE

**Comment by TomBZombie** [comment]
I've fixed most of the problems with the commit above. The improvements are:

- PDO::ATTR_ERRMODE now has zero effect, Silent, exception the behaviour is (almost) the same and is not changed at all when passed into Maphper\DataSource\Database
- There is now a $mapper->getErrors() method which returns an array of exceptions that have been caught. This could be improved but it's the easiest way to get the most information about the errors
- Only exceptions from SELECT queries are suppressed and stored in $mapper->getErrors() 
- Exceptions generated from INSERT statements (that would indicate lost data) are essentially not caught by maphper at all and will be thrown and catchable as normal.
